source 'https://rubygems.org'
gem 'pg'
gem 'rails', '~> 6.1'
gem 'puma', '~> 4.3.7'
gem 'jbuilder', '~> 2.10.0'
gem 'bootsnap'
gem 'rack-cors', '~> 1.1.1'
gem 'scrumship-client', '1.0.19'
gem 'annotate', '3.1.1'
gem 'devise-jwt'
gem 'cancancan'

group :development, :test do
  gem 'byebug', '11.1.3', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '3.3.3'
  gem 'spring', '2.1.1'
  gem 'spring-watcher-listen', '~> 2.0.1'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
